"""Tests for cairn.accessvars — the declarative_access vars exporter.

Two layers:
  - CLI end-to-end on the programmatic rootfs fixture (Linux/macOS only),
    pinning the cross-repo contract shape the linux-access molecule scenario
    mirrors in molecule/default/files/molecule-access-vars.yml.
  - Pure derive_access_vars() tests on synthetic model dicts — the rootfs
    fixture cannot fake file ownership without root, so ownership rules are
    exercised synthetically.

The emitted YAML is parsed back with a test-local mini-parser so the test
suite stays PyYAML-free; one importorskip'd test cross-checks against real
PyYAML when the dev environment has it.
"""

from __future__ import annotations

import json
import sys

import pytest

from cairn import accessvars
from conftest import install_app

pytestmark_linux = pytest.mark.skipif(
    sys.platform == "win32", reason="rootfs fixture builds a POSIX tree")


# ---------------------------------------------------------------------------
# Mini YAML-subset parser (scalars, block lists, one-line flow maps)
# ---------------------------------------------------------------------------

def _unq(v: str):
    if v == "true":
        return True
    if v == "false":
        return False
    if v.startswith("'") and v.endswith("'"):
        return v[1:-1].replace("''", "'")
    return v


def _load_vars(text: str) -> dict:
    data: dict = {}
    current = None
    for raw in text.splitlines():
        s = raw.strip()
        if not s or s.startswith("#") or s == "---":
            continue
        if raw.startswith("  - "):
            item = s[2:].strip()
            if item.startswith("{"):
                entry = {}
                for part in item.strip("{} ").split(","):
                    k, _, v = part.partition(":")
                    entry[k.strip()] = _unq(v.strip())
                data[current].append(entry)
            else:
                data[current].append(_unq(item))
        elif s.endswith(":"):
            current = s[:-1]
            data[current] = []
        else:
            k, _, v = s.partition(":")
            data[k.strip()] = _unq(v.strip())
    return data


# ---------------------------------------------------------------------------
# CLI end-to-end on the fixture rootfs
# ---------------------------------------------------------------------------

EXPECTED_CONTRACT = {
    "declarative_access_profile_name": "myapp",
    "declarative_access_sudo": True,
    "declarative_access_services": ["myapp", "myapp-agent", "myapp-maintenance"],
    "declarative_access_timers": ["myapp-maintenance"],
    "declarative_access_quadlets": ["myapp-web"],
    "declarative_access_linger": True,
    "declarative_access_linger_users": ["dev1"],
    "declarative_access_files_modify": [
        "/etc/containers/systemd/myapp-web.container",
        "/etc/systemd/system/myapp-agent.service",
        "/etc/systemd/system/myapp-maintenance.service",
        "/etc/systemd/system/myapp-maintenance.timer",
        "/etc/systemd/system/myapp.service",
    ],
    "declarative_access_folders_modify": ["/etc/myapp", "/var/lib/myapp"],
    "declarative_access_folders_read": ["/var/log/myapp"],
}


@pytest.fixture
def access_vars_run(run_cli, linux_rootfs, rootfs_config, tmp_path):
    """Init baseline, install the app, capture footprint + access vars."""
    root = linux_rootfs()
    cfg_path, _cfg = rootfs_config()
    rc, _out, _err = run_cli("files", "init", "-c", cfg_path,
                             "--root", str(root), "--force")
    assert rc == 0
    install_app(root)

    report = tmp_path / "footprint.json"
    vars_file = tmp_path / "myapp-access.yml"
    rc, _out, err = run_cli("footprint", "-c", cfg_path, "--root", str(root),
                            "--app", "myapp", "--report", str(report),
                            "--access-vars", str(vars_file))
    assert rc == 1  # changes present; the vars write does not alter drift rc
    assert "ansible access vars written" in err
    return report, vars_file.read_text(encoding="utf-8")


@pytestmark_linux
def test_contract_shape_matches_fixture(access_vars_run):
    _report, text = access_vars_run
    assert _load_vars(text) == EXPECTED_CONTRACT


@pytestmark_linux
def test_header_and_provenance(access_vars_run):
    _report, text = access_vars_run
    assert text.startswith("---\n")
    assert "generated by cairn" in text
    assert "usc.declarative_access" in text
    assert "intentionally NOT set here" in text


@pytestmark_linux
def test_no_user_group_keys_ever(access_vars_run):
    _report, text = access_vars_run
    parsed = _load_vars(text)
    assert "declarative_access_user" not in parsed
    assert "declarative_access_group" not in parsed


@pytestmark_linux
def test_deterministic_rendering(access_vars_run):
    report, text = access_vars_run
    model = json.loads(report.read_text(encoding="utf-8"))
    assert accessvars.render_access_vars(model) == text
    assert accessvars.render_access_vars(model) == accessvars.render_access_vars(model)


@pytestmark_linux
def test_standalone_subcommand_from_json(access_vars_run, run_cli, tmp_path):
    report, text = access_vars_run
    out = tmp_path / "standalone.yml"
    rc, _o, _e = run_cli("access-vars", str(report), "-o", str(out))
    assert rc == 0
    assert out.read_text(encoding="utf-8") == text


@pytestmark_linux
def test_standalone_stdout_default(access_vars_run, run_cli):
    report, text = access_vars_run
    rc, out, _e = run_cli("access-vars", str(report))
    assert rc == 0
    assert out == text


def test_standalone_missing_file_exits_2(run_cli):
    rc, _o, err = run_cli("access-vars", "/nonexistent/footprint.json")
    assert rc == 2
    assert "cannot read footprint JSON" in err


def test_standalone_rejects_non_install_footprint(run_cli, tmp_path):
    bad = tmp_path / "notes.json"
    bad.write_text(json.dumps({"hello": "world"}), encoding="utf-8")
    rc, _o, err = run_cli("access-vars", str(bad))
    assert rc == 2
    assert "install-time footprint" in err


def test_standalone_rejects_windows_footprint(run_cli, tmp_path):
    win = tmp_path / "win.json"
    win.write_text(json.dumps({
        "footprint_type": "install_time",
        "services": {"windows_services": []},
    }), encoding="utf-8")
    rc, _o, err = run_cli("access-vars", str(win))
    assert rc == 2
    assert "Linux-only" in err


# ---------------------------------------------------------------------------
# Pure derivation tests on synthetic models
# ---------------------------------------------------------------------------

def _mk_model(**over) -> dict:
    model = {
        "schema_version": "1.0",
        "footprint_type": "install_time",
        "generated_at": "2026-01-01T00:00:00+00:00",
        "application": "myapp",
        "services": {"systemd_units": [], "quadlets": []},
        "filesystem": {"added_by_category": {}, "modified": [], "deleted": []},
        "principals": {"users_added": [], "groups_added": [],
                       "membership_changes": []},
    }
    model.update(over)
    return model


def _svc(name, path=None, unit_type=None, **fields) -> dict:
    unit = {"name": name,
            "path": path or f"/etc/systemd/system/{name}",
            "unit_type": unit_type or name.rsplit(".", 1)[-1]}
    unit.update(fields)
    return unit


def _entry(path, *, is_dir=False, owner="root", group="root",
           mode_octal="0o755") -> dict:
    return {"path": path, "is_dir": is_dir, "owner": owner, "group": group,
            "mode_octal": mode_octal, "category": "", "mode_symbolic": "",
            "size": 0, "sha256": None}


def test_ownership_emitted_for_install_added_principal():
    model = _mk_model()
    model["principals"]["users_added"] = [{"name": "myapp"}]
    model["filesystem"]["added_by_category"] = {
        "state_dir": [_entry("/var/lib/myapp", is_dir=True, owner="myapp",
                             group="myapp", mode_octal="0o2750")],
    }
    data = accessvars.derive_access_vars(model)
    assert data["declarative_access_ownership"] == [
        {"path": "/var/lib/myapp", "owner": "myapp", "group": "myapp",
         "mode": "2750"}]


def test_ownership_skipped_for_foreign_owner():
    model = _mk_model()
    model["filesystem"]["added_by_category"] = {
        "state_dir": [_entry("/var/lib/myapp", is_dir=True, owner="builder",
                             group="staff")],
    }
    data = accessvars.derive_access_vars(model)
    assert "declarative_access_ownership" not in data
    assert data["declarative_access_folders_modify"] == ["/var/lib/myapp"]


def test_ownership_mode_zero_padded():
    model = _mk_model()
    model["principals"]["groups_added"] = [{"name": "myapp"}]
    model["filesystem"]["added_by_category"] = {
        "config": [_entry("/etc/myapp", is_dir=True, group="myapp",
                          mode_octal="0o755")],
    }
    data = accessvars.derive_access_vars(model)
    assert data["declarative_access_ownership"][0]["mode"] == "0755"


def test_template_units_excluded():
    model = _mk_model()
    model["services"]["systemd_units"] = [_svc("worker@.service")]
    data = accessvars.derive_access_vars(model)
    assert "declarative_access_services" not in data
    assert "declarative_access_sudo" not in data


def test_user_scope_units_excluded():
    model = _mk_model()
    model["services"]["systemd_units"] = [
        _svc("mine.service", path="/etc/systemd/user/mine.service")]
    data = accessvars.derive_access_vars(model)
    assert "declarative_access_services" not in data


def test_timer_bare_name():
    model = _mk_model()
    model["services"]["systemd_units"] = [_svc("nightly.timer")]
    data = accessvars.derive_access_vars(model)
    assert data["declarative_access_timers"] == ["nightly"]
    assert data["declarative_access_sudo"] is True


def test_rootless_quadlet_becomes_linger_only():
    model = _mk_model()
    model["services"]["quadlets"] = [
        {"name": "side.container", "service_name": "side.service",
         "rootless": True, "owner": "dev1"},
    ]
    data = accessvars.derive_access_vars(model)
    assert "declarative_access_quadlets" not in data
    assert data["declarative_access_linger"] is True
    assert data["declarative_access_linger_users"] == ["dev1"]


def test_quadlet_generated_name_used():
    model = _mk_model()
    model["services"]["quadlets"] = [
        {"name": "db.pod", "service_name": "db-pod.service",
         "rootless": False, "owner": None},
    ]
    data = accessvars.derive_access_vars(model)
    assert data["declarative_access_quadlets"] == ["db-pod"]


def test_nested_folders_folded():
    model = _mk_model()
    model["filesystem"]["added_by_category"] = {
        "config": [_entry("/etc/myapp", is_dir=True),
                   _entry("/etc/myapp/conf.d", is_dir=True)],
    }
    data = accessvars.derive_access_vars(model)
    assert data["declarative_access_folders_modify"] == ["/etc/myapp"]


def test_folder_read_subsumed_by_modify_dropped():
    model = _mk_model()
    model["services"]["systemd_units"] = [
        _svc("app.service", state_directory=["myapp"]),
    ]
    model["filesystem"]["added_by_category"] = {
        "log_dir": [_entry("/var/lib/myapp/logs", is_dir=True)],
    }
    data = accessvars.derive_access_vars(model)
    assert data["declarative_access_folders_modify"] == ["/var/lib/myapp"]
    assert "declarative_access_folders_read" not in data


def test_files_under_granted_folder_dropped():
    model = _mk_model()
    model["filesystem"]["added_by_category"] = {
        "config": [_entry("/etc/myapp", is_dir=True)],
        "quadlet": [_entry("/etc/myapp/web.container"),
                    _entry("/etc/containers/systemd/web.container")],
    }
    data = accessvars.derive_access_vars(model)
    assert data["declarative_access_files_modify"] == [
        "/etc/containers/systemd/web.container"]


def test_directive_derived_folders_present_without_diff_entries():
    model = _mk_model()
    model["services"]["systemd_units"] = [
        _svc("app.service", state_directory=["myapp"],
             configuration_directory=["myapp"], cache_directory=["myapp"],
             logs_directory=["myapp"]),
    ]
    data = accessvars.derive_access_vars(model)
    assert data["declarative_access_folders_modify"] == [
        "/etc/myapp", "/var/cache/myapp", "/var/lib/myapp"]
    assert data["declarative_access_folders_read"] == ["/var/log/myapp"]


def test_empty_footprint_minimal_output():
    model = _mk_model()
    data = accessvars.derive_access_vars(model)
    assert data == {"declarative_access_profile_name": "myapp"}
    text = accessvars.render_access_vars(model)
    assert "no systemd service/timer/quadlet or folder surface" in text
    assert "declarative_access_sudo" not in text


def test_pyyaml_cross_parse():
    yaml = pytest.importorskip("yaml")
    model = _mk_model()
    model["services"]["systemd_units"] = [_svc("app.service"),
                                          _svc("nightly.timer")]
    model["services"]["quadlets"] = [
        {"name": "web.container", "service_name": "web.service",
         "rootless": False, "owner": None},
    ]
    model["principals"]["users_added"] = [{"name": "myapp"}]
    model["filesystem"]["added_by_category"] = {
        "state_dir": [_entry("/var/lib/myapp", is_dir=True, owner="myapp",
                             group="myapp", mode_octal="0o2750")],
        "systemd_unit": [_entry("/etc/systemd/system/app.service")],
    }
    text = accessvars.render_access_vars(model)
    assert yaml.safe_load(text) == _load_vars(text)
